ALTER TABLE EMPLOYEES ALTER COLUMN id RESTART WITH (SELECT MAX(ID)+1 from EMPLOYEES);

INSERT INTO ADMINS (ID, CREATED_AT, EMAIL, PASSWORD, ROLE, USERNAME)
SELECT 1, CURRENT_TIMESTAMP, 'admin@example.com',
       '$2a$10$iYRlcKgJH6wKhM.mPGD75eqT9yHeVHs4RCNwP9eV9LDgeFoAOIL1O',
       'ADMIN', 'admin'
WHERE NOT EXISTS (
    SELECT 1 FROM ADMINS WHERE USERNAME = 'admin'
);
